Create
JuanPablo2655/itsc-3155-module-9-assignment pull request #3
Opened 2022-10-23 02:19 UTC by katurian

added form template and create_movie() logic

2022-10-23 02:21 UTC, JuanPablo2655 requested changes

2022-10-23 02:21 UTC, JuanPablo2655 commented on templates/create_movies_form.html
> +</head>
Probably best to move it in `_layout.html`

2022-10-23 23:03 UTC, katurian commented
Okay, will do.

2022-10-26 01:14 UTC, JuanPablo2655 requested changes
I suggest testing before committing any changes

2022-10-26 01:14 UTC, JuanPablo2655 commented on tests/unit/test_create_movie.py
> +movies._db.__init__()
```suggestion

```

2022-10-26 01:14 UTC, JuanPablo2655 commented on tests/unit/test_create_movie.py
> +    movies._db.__init__()
```suggestion
    movies.__init__()
    currentMovies = movies.get_all_movies()
```

2022-10-26 01:14 UTC, JuanPablo2655 commented on tests/unit/test_create_movie.py
> +    get_movie_repository.create_movie('Wings', 'Larisa Shepitko', 5)
```suggestion
    movies.create_movie('Mulholland Drive', 'David Lynch', 5)
    assert len(currentMovies) == 1
    movies.create_movie('Wings', 'Larisa Shepitko', 5)
```

2022-10-26 01:49 UTC, JuanPablo2655 approved these changes
LGTM

2022-10-26 01:54 UTC, merged